### ISSUE TITLE
SunEditor toolbar menu functions 

### ISSUE THREAD

**Issue by roabol** [primefaces/community#1948]
I'm starting with SunEditor and noticed a problem with the popup menu: font, font size and format.

See the problem in the image.

![image](https://github.com/primefaces/community/assets/2237805/118c152d-d4fa-4e05-80a5-628338f16a76)

https://www.primefaces.org/showcase-ext/sections/sunEditor/basicUsage.jsf;jsessionid=node0npitb1wl854f3kbbnogis83x14519201.node0

**Comment by melloware** [comment]
@roabol please try PFE 13.0.10 that has been fixed see: https://github.com/primefaces-extensions/primefaces-extensions/issues/1275
