### ISSUE TITLE
Apollo Theme: Radio button shows twice

### ISSUE THREAD

**Issue by arussell-wiseconn** [primefaces/community#1965]
Submitting this as an issue to get some eyes on it. Please let me know if i need to modify this issue to have my comment directly as the issue description. Or if this was ok. 

### Discussed in https://github.com/orgs/primefaces/discussions/1781

<div type='discussions-op-text'>

<sup>Originally posted by **chrishj59** April 27, 2024</sup>
Hi,

Using the Apollo theme, my Radio button shows twice, once with the non-Primefaces look and once with the Primefaces look.
Here is the code:
```
<RadioButton
	inputId={attrib.id.toString()}
	name={title}
	value={attrib.id}
	onChange={(e) => onSetRadio(e)}
	checked={sizeId === attrib.id}
    />
    <label htmlFor={attrib.id.toString()} className="ml-2">
	{attrib.title}
    </label>
```
 
I think this may be waiting for an update to the Apollo theme.
Please let me know when the theme will be updated.

Thanks</div>

**Comment by melloware** [comment]
Similar to issue: https://github.com/primefaces/primereact/issues/6181

Please see this guide to upgrade your template CSS: https://github.com/primefaces/primereact/wiki/Migration-Guide-for-Templates
