### ISSUE TITLE
Compatibility Issue: Apollo Theme with PrimeReact on Next.js 14.2 - MultiSelect Checkbox Styling Issue

### ISSUE THREAD

**Issue by Brunoiooo** [primefaces/community#2971]
### Discussed in https://github.com/orgs/primefaces/discussions/2929

<div type='discussions-op-text'>

<sup>Originally posted by **Brunoiooo** October 28, 2024</sup>
I would like to report a compatibility issue between the Apollo theme version for Next.js and the PrimeReact library. After updating the Next.js framework to version 14.2, I encountered visual issues with the PrimeReact MultiSelect component—checkboxes are not correctly hidden or styled, resulting in a visible standalone frame with an unstyled checkbox above it.

While the component does correctly select options, the unstyled checkbox issue affects the aesthetics and consistency of the user interface. My analysis suggests that this may be due to differences in the way checkboxes are generated across Next.js versions.

Is there any possibility of implementing adjustments in the Apollo theme to ensure full compatibility with the newer version of Next.js? This would allow us to take advantage of the latest framework features while maintaining a polished component appearance.

![image](https://github.com/user-attachments/assets/208aeb93-d4a7-4d81-8714-d7bcd1ab514f)</div>

**Comment by Brunoiooo** [comment]
@onursenture @tandraschko @melloware Could You help

**Comment by tandraschko** [comment]
Im not active in primereact

**Comment by tandraschko** [comment]
Please use the primereact issue tracker
