### ISSUE TITLE
Virtual Scroll Jumping Backwards

### ISSUE THREAD

**Issue by dsgnow** [primefaces/community#637]
### Discussed in https://github.com/orgs/primefaces/discussions/353

<div type='discussions-op-text'>

<sup>Originally posted by **msixfour** October 31, 2023</sup>
if we have a textarea next to a dropdown and pass [autoresize]=true to it, the virtual scroll doesn't work correctly.
Code to reproduce:

```
<div class="card flex justify-content-center">
  <textarea pInputTextarea rows="1" [autoResize]="true"></textarea>
  <p-dropdown
    [options]="items"
    [(ngModel)]="selectedItem"
    placeholder="Select Item"
    [virtualScroll]="true"
    [virtualScrollItemSize]="38"
  ></p-dropdown>
</div>
```
```
constructor() {
    this.items = [];
    for (let i = 0; i < 50; i++) {
      this.items.push({ label: 'Item ' + i, value: 'Item ' + i });
    }
  }
```

@cetincakiroglu 
codesandbox example:  https://codesandbox.io/s/primeng-dropdown-virtualscroll-demo-forked-8tn6m7?file=/src/app/demo/dropdown-virtualscroll-demo.html

 </div>

**Comment by cetincakiroglu** [comment]
Hi,

The issue is opened in the wrong repo, could you please open it on PrimeNG and tag me?
